services:
  db:
    ports:
      - "5433:5432"

  api:
    environment:
      APP_ENV: development
    command: uvicorn lawn_api.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - /opt/apps/lawn/api/src:/app/src
      - /opt/apps/lawn/api/tests:/app/tests
    ports:
      - "8000:8000"

  web:
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    working_dir: /app
    volumes:
      - /opt/apps/lawn/web:/app
      - /app/node_modules
    ports:
      - "3001:3000"
